# PURPOSE - Manage multiple containers docker-compose.yml -> docker compose up -> containers,network,volumes, env
# Building image ->
# docker compose up --build -d (building image in detach mode)
# -> docker compose exec app alembic upgrade head (for migrations)
# -> docker compose down (stopping containers)
# -> docker compose up (running the service after building)
services:
  app:
    build: .

    ports:
      - "8000:8000"

    env_file:
      - .env