"""Add Profile pic model

Revision ID: 5ccf467427d2
Revises: 6c4187494a72
Create Date: 2026-07-28 01:05:56.333787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccf467427d2'
down_revision: Union[str, Sequence[str], None] = '6c4187494a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_pic',
    sa.Column('pic_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('original_name', sa.String(length=200), nullable=False),
    sa.Column('saved_as', sa.String(length=255), nullable=False),
    sa.Column('folder', sa.String(length=200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pic_id'),
    sa.UniqueConstraint('profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profile_pic_pic_id'), 'profile_pic', ['pic_id'], unique=False)
    op.create_index(op.f('ix_profile_pic_saved_as'), 'profile_pic', ['saved_as'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_pic_saved_as'), table_name='profile_pic')
    op.drop_index(op.f('ix_profile_pic_pic_id'), table_name='profile_pic')
    op.drop_table('profile_pic')
    # ### end Alembic commands ###
