"""Fix vote unique constraint

Revision ID: fcc7f21c38ff
Revises: 8c03d5da8583
Create Date: 2026-06-27 00:56:49.717748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc7f21c38ff'
down_revision: Union[str, Sequence[str], None] = '8c03d5da8583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('posts', 'post',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=50000),
               existing_nullable=False)
    op.drop_constraint(op.f('votes_vote_key'), 'votes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('votes_vote_key'), 'votes', ['vote'], postgresql_nulls_not_distinct=False)
    op.alter_column('posts', 'post',
               existing_type=sa.String(length=50000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
